CREATE TABLE Firms(
	Id   UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	Name NVARCHAR(64)     NOT NULL 
);

CREATE TABLE Employees(
    Id        UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FirmId    UNIQUEIDENTIFIER NOT NULL,
    Name      NVARCHAR(100) NOT NULL,
    Birthdate DATETIME2        NOT NULL
);
 
CREATE TABLE Products(
    Id    UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name  NVARCHAR(256)    NOT NULL,
    Price MONEY            NOT NULL
);

CREATE TABLE Sales(
    Id         UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    EmployeeId UNIQUEIDENTIFIER NOT NULL,
    ProductId  UNIQUEIDENTIFIER NOT NULL,
    Quantity   INT              NOT NULL,
    Moment     DATETIME2        NOT NULL
);